### ISSUE TITLE
Publish the package types

### ISSUE THREAD

**Issue by abdonrd** [samthor/but-unzip#2]
Would it be possible to publish the package types?
It would help when using this library in TypeScript.

Thank you!

**Comment by samthor** [comment]
I've pushed `but-unzip@0.1.1` which includes TypeScript types. Thanks for the motivation! 🎉

**Comment by abdonrd** [comment]
Thanks Sam! 🎉

**Comment by abdonrd** [comment]
@samthor I think you need to add the types inside the `package.json > exports`:

https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

**Comment by samthor** [comment]
I had put it as a top-level `"types": "index.d.ts"`, but I've added that in `but-unzip@0.1.2`, I get how stubborn this space can be.
